name: cached_custom_marker
description: "Cached Custom Marker optimizes Flutter map apps by managing custom markers. It automates image downloading, caching, and conversion for Google Maps, enhancing performance and user experience."
version: 0.0.3+1
homepage: https://github.com/ahmedsaleh210/cached_custom_marker
repository: https://github.com/ahmedsaleh210/cached_custom_marker
license: MIT

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  google_maps_flutter: ^2.7.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
